pipeline {
    
    agent { label 'jenkins-agent' }


    triggers {
        githubPush()
    }

    environment {
        APP_NAME   = "banking-app"
        DOCKER_USER = "jhamadhav2025"  
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/madhav-jha/banking-app-devopsproject.git'
            }
        }

        stage('Maven Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh "docker build -t ${APP_NAME} ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DH_USER',
                    passwordVariable: 'DH_PASS'
                )]) {
                    sh """
                        echo "$DH_PASS" | docker login -u "$DH_USER" --password-stdin
                        docker tag ${APP_NAME} $DH_USER/${APP_NAME}:latest
                        docker push $DH_USER/${APP_NAME}:latest
                    """
                }
            }
        }

        stage('Deploy to App Server') {
            steps {
                
                sh """
                    ssh -o StrictHostKeyChecking=no -i ~/.ssh/madhav-devops-key.pem ubuntu@13.52.112.32 '
                        docker pull ${DOCKER_USER}/${APP_NAME}:latest &&
                        docker stop ${APP_NAME} || true &&
                        docker rm ${APP_NAME} || true &&
                        docker run -d -p 8080:8082 --name ${APP_NAME} ${DOCKER_USER}/${APP_NAME}:latest
                    '
                """
            }
        }
    }

    post {
        success {
            emailext(
                subject: "Jenkins Build SUCCESS: \${JOB_NAME} #\${BUILD_NUMBER}",
                body: "Build SUCCESSFUL for job \${JOB_NAME} #\${BUILD_NUMBER}\n\nCheck Jenkins for more details.",
                to: "jhamadhav2025@gmail.com"
            )
        }
        failure {
            emailext(
                subject: "Jenkins Build FAILED: \${JOB_NAME} #\${BUILD_NUMBER}",
                body: "Build FAILED for job \${JOB_NAME} #\${BUILD_NUMBER}\n\nPlease check console output.",
                to: "jhamadhav2025@gmail.com"
            )
        }
    }
}
