pipeline {

    
    agent { label 'jenkins-agent' }

    
    triggers {
        githubPush()
    }

    
    environment {
        APP_NAME    = "banking-app"
        DOCKER_USER = "jhamadhav2025"
        DEPLOY_HOST = "13.52.112.32"
        PEM_PATH    = "/home/ubuntu/.ssh/madhav-devops-key.pem"
    }

    stages {

        
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/madhav-jha/banking-app-devopsproject.git'
            }
        }

        
        stage('Maven Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

       
        stage('Docker Build') {
            steps {
                dir('app') {
                    sh "docker build -t ${APP_NAME} ."
                }
            }
        }

       
        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DH_USER',
                    passwordVariable: 'DH_PASS'
                )]) {
                    sh """
                        echo "$DH_PASS" | docker login -u "$DH_USER" --password-stdin
                        docker tag ${APP_NAME} ${DH_USER}/${APP_NAME}:latest
                        docker push ${DH_USER}/${APP_NAME}:latest
                    """
                }
            }
        }

       
        stage('Deploy to EC2') {
            steps {
                sh """
                    ssh -o StrictHostKeyChecking=no -i ${PEM_PATH} ubuntu@${DEPLOY_HOST} '
                        docker pull ${DOCKER_USER}/${APP_NAME}:latest &&
                        docker stop ${APP_NAME} || true &&
                        docker rm ${APP_NAME} || true &&
                        docker run -d -p 8080:8082 --name ${APP_NAME} ${DOCKER_USER}/${APP_NAME}:latest
                    '
                """
            }
        }
    }

    
    post {
        success {
            emailext(
                subject: "SUCCESS: ${JOB_NAME} #${BUILD_NUMBER}",
                body: "Build SUCCESSFUL.\nJob: ${JOB_NAME}\nBuild: #${BUILD_NUMBER}",
                to: "jhamadhav2025@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "FAILED: ${JOB_NAME} #${BUILD_NUMBER}",
                body: "Build FAILED.",
                to: "jhamadhav2025@gmail.com"
            )
        }
    }
}
